name: dart_ast_viewer
description: dart_ast_viewer

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  analyzer: 2.3.0
  flutter_hooks: 0.18.0
  graphview: 1.0.0-nullsafety.1
  path: 1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.0

flutter:
  uses-material-design: true

